.PHONY: clean All

All:
	@echo "----------Building project:[ Chrono_Duration_Types - Debug ]----------"
	@cd "Chrono_Duration_Types" && "$(MAKE)" -f  "Chrono_Duration_Types.mk"
clean:
	@echo "----------Cleaning project:[ Chrono_Duration_Types - Debug ]----------"
	@cd "Chrono_Duration_Types" && "$(MAKE)" -f  "Chrono_Duration_Types.mk" clean
