.PHONY: clean All

All:
	@echo "----------Building project:[ Tuples_in_Cpp17 - Debug ]----------"
	@cd "Tuples_in_Cpp17" && "$(MAKE)" -f  "Tuples_in_Cpp17.mk"
clean:
	@echo "----------Cleaning project:[ Tuples_in_Cpp17 - Debug ]----------"
	@cd "Tuples_in_Cpp17" && "$(MAKE)" -f  "Tuples_in_Cpp17.mk" clean
