.PHONY: clean All

All:
	@echo "----------Building project:[ Forwarding_References - Debug ]----------"
	@cd "Forwarding_References" && "$(MAKE)" -f  "Forwarding_References.mk"
clean:
	@echo "----------Cleaning project:[ Forwarding_References - Debug ]----------"
	@cd "Forwarding_References" && "$(MAKE)" -f  "Forwarding_References.mk" clean
