.PHONY: clean All

All:
	@echo "----------Building project:[ Containers - Debug ]----------"
	@cd "Containers" && "$(MAKE)" -f  "Containers.mk"
clean:
	@echo "----------Cleaning project:[ Containers - Debug ]----------"
	@cd "Containers" && "$(MAKE)" -f  "Containers.mk" clean
