.PHONY: clean All

All:
	@echo "----------Building project:[ Miscellaneous_Features - Debug ]----------"
	@cd "Miscellaneous_Features" && "$(MAKE)" -f  "Miscellaneous_Features.mk"
clean:
	@echo "----------Cleaning project:[ Miscellaneous_Features - Debug ]----------"
	@cd "Miscellaneous_Features" && "$(MAKE)" -f  "Miscellaneous_Features.mk" clean
