.PHONY: clean All

All:
	@echo "----------Building project:[ File_Streams_Assignment_2 - Debug ]----------"
	@cd "File_Streams_Assignment_2" && "$(MAKE)" -f  "File_Streams_Assignment_2.mk"
clean:
	@echo "----------Cleaning project:[ File_Streams_Assignment_2 - Debug ]----------"
	@cd "File_Streams_Assignment_2" && "$(MAKE)" -f  "File_Streams_Assignment_2.mk" clean
